### PR TITLE
Dev airdrop

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @wangdayong228)

___
*[main.go, line 8 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0FXjo6TRrON6TWgn9:-MM0FXjo6TRrON6TWgnA:b-qinydv) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/main.go#L8)):*
> ```Go
> 
> 	"github.com/Conflux-Chain/conflux-toolkit/account"
> 	airdrop "github.com/Conflux-Chain/conflux-toolkit/airdrop"
> ```

unnecessary alias.
___
*[airdrop/util.go, line 7 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0Hpwn5TFhr1duJOkD:-MM0Hpwn5TFhr1duJOkE:b74s4eh) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L7)):*
> ```Go
> var airdropListFile string
> var airdropNumber int
> var from string
> ```

reuse account.addFromVar? just change the method to public
___
*[airdrop/util.go, line 8 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0Hgr7DBJYFU7v_wOV:-MM0Hgr7DBJYFU7v_wOW:bck322r) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L8)):*
> ```Go
> var airdropNumber int
> var from string
> var perBatchNum int
> ```

suggest to move to the airdrop/toot.go file, since these variables are used only for airdrop command.
___
*[airdrop/util.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0ILm3-MloO6ib6EWe:-MM0ILm3-MloO6ib6EWf:b3ay2si) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L13)):*
> ```Go
> func AddAirdropListFileVar(cmd *cobra.Command) {
> 	cmd.PersistentFlags().StringVar(&airdropListFile, "list", "", "airdrop list file path")
> 	cmd.MarkPersistentFlagRequired("airdrop")
> ```

it should be `list`
___
*[airdrop/util.go, line 18 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0ITPJ7y9esE5jfhin:-MM0ITPJ7y9esE5jfhio:bdd94fw) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L18)):*
> ```
> representds
> ```

typo.

My suggestion: "airdrop value in CFX"
___
*[airdrop/util.go, line 19 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0If4xEbhwMbMx87KT:-MM0If4xEbhwMbMx87KU:b-fkmfmp) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L19)):*
> ```Go
> func AddAirdropNumberVar(cmd *cobra.Command) {
> 	cmd.PersistentFlags().IntVar(&airdropNumber, "number", 0, "airdrop number, the unit is CFX, 1 representds 1 CFX")
> 	cmd.MarkPersistentFlagRequired("airdrop")
> ```

`list`, not `airdrop`
___
*[rpc/util.go, line 17 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0HIczCIrNdetvbRFb:-MM0HIczCIrNdetvbRFc:b8n6rlh) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/rpc/util.go#L17)):*
> ```Go
> func AddURLVar(cmd *cobra.Command) {
> 	// cmd.PersistentFlags().StringVar(&url, "url", "http://main.confluxrpc.org", "Conflux RPC URL")
> 	cmd.PersistentFlags().StringVar(&url, "url", "http://test.confluxrpc.org", "Conflux RPC URL")
> ```

Please use mainnet rpc by default.
___
*[util/util.go, line 59 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0GNgW2jn1TQd70Pmg:-MM0GNgW2jn1TQd70Pmh:b-4qsygm) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/util/util.go#L59)):*
> ```Go
> 	if err != nil {
> 		fmt.Printf(format, a...)
> 		fmt.Printf("--- error:%v", err)
> ```

better to add a space after colon (before error message)

**Review by boqiu — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)* status: all files reviewed, 8 unresolved discussions (waiting on @wangdayong228)

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)* status: all files reviewed, 10 unresolved discussions (waiting on @wangdayong228)

___
*[go.mod, line 8 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM473Dm9rS3ZT1-kOQR:-MM473Dm9rS3ZT1-kOQS:bqsfbnv) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/go.mod#L8)):*
> ```XML
> 	github.com/Conflux-Chain/go-conflux-sdk v0.4.6
> 	github.com/emirpasic/gods v1.12.0
> 	github.com/howeyc/gopass v0.0.0-20190910152052-7cb4b85ec19c
> ```

Suggest to update the go.sum as well.
___
*[account/util.go, line 18 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM47PXpCBnRDX_dGIXE:-MM47PXpCBnRDX_dGIXF:b-guqkv6) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/account/util.go#L18)):*
> ```Go
> 
> var (
> 	Account  string
> ```

Why changed to `public`?

Better to use `MustParseAccount` to get the tx sender address.
___
*[rpc/util.go, line 17 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM48Cew8-9vc1fc1Tto:-MM48Cew8-9vc1fc1Ttp:b-8q3k7d) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/rpc/util.go#L17)):*
> ```Go
> func AddURLVar(cmd *cobra.Command) {
> 	cmd.PersistentFlags().StringVar(&url, "url", "http://main.confluxrpc.org", "Conflux RPC URL")
> 	// cmd.PersistentFlags().StringVar(&url, "url", "http://test.confluxrpc.org", "Conflux RPC URL")
> ```

Please remove this line, and use `--url` for test purpose.
___
*[transfer/root.go, line 31 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM48UZQ5n8t3GV0Zp9C:-MM48UZR-P0Fk-TgNRUx:b-is859m) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/transfer/root.go#L31)):*
> ```Go
> 	// path for record result
> 	resultPath      = "./airdrop_result"
> 	defaultGasPrice = types.NewBigInt(1)
> ```

could use account.AddGasPriceVar instead

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)* status: all files reviewed, 5 unresolved discussions (waiting on @wangdayong228)

___
*[transfer/root.go, line 46 at r3](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM4CY70CMR_-9VxCqNE:-MM4CY70CMR_-9VxCqNF:bva9ome) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/7a3ac5a4f177093258d09ae06dbfda6961ae628e/transfer/root.go#L46)):*
> ```Go
> 	rootCmd.PersistentFlags().StringVar(&receiverListFile, "receivers", "", "receiver list file path")
> 	rootCmd.MarkPersistentFlagRequired("receivers")
> 	rootCmd.PersistentFlags().UintVar(&receiveNumber, "number", 1, "send value in CFX")
> ```

better to mark as required, `transfer value` is very important for user.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @boqiu)

___
*[go.mod, line 8 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM473Dm9rS3ZT1-kOQR:-MM4T04i6CLKQTEf4cEE:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/go.mod#L8)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to update the go.sum as well.
</blockquote></details>

done
___
*[main.go, line 8 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0FXjo6TRrON6TWgn9:-MM4T-8EBT0zy7nlBk4F:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/main.go#L8)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

unnecessary alias.
</blockquote></details>

done
___
*[account/util.go, line 18 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM47PXpCBnRDX_dGIXE:-MM4Sz9YBD6IDfaYAcdt:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/account/util.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why changed to `public`?

Better to use `MustParseAccount` to get the tx sender address.
</blockquote></details>

done
___
*[airdrop/util.go, line 7 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0Hpwn5TFhr1duJOkD:-MM4SxpZ4X7Y8uKXBIWS:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L7)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

reuse account.addFromVar? just change the method to public
</blockquote></details>

done
___
*[airdrop/util.go, line 8 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0Hgr7DBJYFU7v_wOV:-MM4SyKm87-pDoJYOmnD:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L8)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

suggest to move to the airdrop/toot.go file, since these variables are used only for airdrop command.
</blockquote></details>

done
___
*[airdrop/util.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0ILm3-MloO6ib6EWe:-MM4SwVs2akwH-TvM4Vt:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

it should be `list`
</blockquote></details>

done
___
*[airdrop/util.go, line 18 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0ITPJ7y9esE5jfhin:-MM4SvvMByMFloQmiGGn:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> representds
> ```

typo.

My suggestion: "airdrop value in CFX"
</blockquote></details>

done
___
*[airdrop/util.go, line 19 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0If4xEbhwMbMx87KT:-MM4SvPt4P1HcZo1lSeN:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/airdrop/util.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`list`, not `airdrop`
</blockquote></details>

done
___
*[rpc/util.go, line 17 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0HIczCIrNdetvbRFb:-MM4Sl-i0M9tXwsUngG6:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/rpc/util.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Please use mainnet rpc by default.
</blockquote></details>

done
___
*[rpc/util.go, line 17 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM48Cew8-9vc1fc1Tto:-MM4SpQ56A1DfhLudvUm:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/rpc/util.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Please remove this line, and use `--url` for test purpose.
</blockquote></details>

done
___
*[transfer/root.go, line 31 at r2](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM48UZQ5n8t3GV0Zp9C:-MM4SrEG0KWlyY1Cct33:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/c3b31426a54f4d10e4d2a12584196d3649fc62cf/transfer/root.go#L31)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

could use account.AddGasPriceVar instead
</blockquote></details>

done
___
*[transfer/root.go, line 46 at r3](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM4CY70CMR_-9VxCqNE:-MM4SrqtC2vu-fASB_2W:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/7a3ac5a4f177093258d09ae06dbfda6961ae628e/transfer/root.go#L46)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to mark as required, `transfer value` is very important for user.
</blockquote></details>

done
___
*[util/util.go, line 59 at r1](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-MM0GNgW2jn1TQd70Pmg:-MM4StMU5WoCfrdRhtNr:bb7f2mf) ([raw file](https://github.com/conflux-chain/conflux-toolkit/blob/cfbcea9728ab85ddd1044e3af2544ce3540bd5ee/util/util.go#L59)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to add a space after colon (before error message)
</blockquote></details>

done

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-toolkit/4#-:-MM4UQBc7B3kEhntyV79:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
